/** Auto-generated by scripts/generate_books_catalog.cjs — do not edit manually */
export const catalogBooks = [
  {
    "id": "bk_general_1",
    "title": "[Seppe vanden Broucke, Bart Baesens] Practical Web",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/[Seppe_vanden_Broucke,_Bart_Baesens]_Practical_Web.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/[Seppe_vanden_Broucke,_Bart_Baesens]_Practical_Web.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: [Seppe vanden Broucke, Bart Baesens] Practical Web. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_2",
    "title": "A Practical Guide to Azure DevOps Learn by doing",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1IECq9jvN7zeVQb2fy07RLnTzfzn04v7D/view?usp=sharing",
    "driveFileId": "1IECq9jvN7zeVQb2fy07RLnTzfzn04v7D",
    "localPath": "/uploads/books/A_Practical_Guide_to_Azure_DevOps_Learn_by_doing.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: A Practical Guide to Azure DevOps Learn by doing. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_3",
    "title": "A Practical Introduction to Python Programming Heinold",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/A_Practical_Introduction_to_Python_Programming_Heinold.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/A_Practical_Introduction_to_Python_Programming_Heinold.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: A Practical Introduction to Python Programming Heinold. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_4",
    "title": "Automating.DevOps.with.GitLab.CI.CD.Pipelines",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1QB2Agk81OfkaSdCONIs79hblJdfCQ-5i/view?usp=sharing",
    "driveFileId": "1QB2Agk81OfkaSdCONIs79hblJdfCQ-5i",
    "localPath": "/uploads/books/Automating.DevOps.with.GitLab.CI.CD.Pipelines.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Automating.DevOps.with.GitLab.CI.CD.Pipelines. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_5",
    "title": "AWS interview",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1WE8QeRaMdP8-x_oGOPPfpos-YPxxrVsp/view?usp=sharing",
    "driveFileId": "1WE8QeRaMdP8-x_oGOPPfpos-YPxxrVsp",
    "localPath": "/uploads/books/AWS interview.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS interview. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_6",
    "title": "AWS Learning Roadmap",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1I33gFhoGKoaxlzR_EFLaqNrp_lAgBbms/view?usp=sharing",
    "driveFileId": "1I33gFhoGKoaxlzR_EFLaqNrp_lAgBbms",
    "localPath": "/uploads/books/AWS Learning Roadmap.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS Learning Roadmap. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_7",
    "title": "AWS Basic Interview Questions CloudDost Telegram",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1QH-Pqo4QYV7wQzbeApFPPsk666_ViiXa/view?usp=sharing",
    "driveFileId": "1QH-Pqo4QYV7wQzbeApFPPsk666_ViiXa",
    "localPath": "/uploads/books/AWS_Basic_Interview_Questions_CloudDost_Telegram.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS Basic Interview Questions CloudDost Telegram. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_8",
    "title": "AWS Cerified Cloud Practitioner",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1NyCILEZJJyI1ZAWLAWv2vW_xvRigqFVJ/view?usp=sharing",
    "driveFileId": "1NyCILEZJJyI1ZAWLAWv2vW_xvRigqFVJ",
    "localPath": "/uploads/books/AWS_Cerified_Cloud_Practitioner.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS Cerified Cloud Practitioner. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_9",
    "title": "aws certified solutions architect",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1-etkJ3A6ge0pLmR7noasgxV5YcetMFkj/view?usp=sharing",
    "driveFileId": "1-etkJ3A6ge0pLmR7noasgxV5YcetMFkj",
    "localPath": "/uploads/books/aws_certified_solutions_architect.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: aws certified solutions architect. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_10",
    "title": "AWS Cookbook Recipes for Success on AWS John Culkin, Mike Zazon",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1HhhlzX3Rf4JfeisTHKvfhGZIMdKsiYmm/view?usp=sharing",
    "driveFileId": "1HhhlzX3Rf4JfeisTHKvfhGZIMdKsiYmm",
    "localPath": "/uploads/books/AWS_Cookbook_Recipes_for_Success_on_AWS_John_Culkin,_Mike_Zazon.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS Cookbook Recipes for Success on AWS John Culkin, Mike Zazon. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_11",
    "title": "AWS vs Azure vs Google vs IBM vs Oracle vs Alibaba A detailed comparison",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1-dtUGQrdAhJBdnSIiy1YVn4xFClPFrYB/view?usp=sharing",
    "driveFileId": "1-dtUGQrdAhJBdnSIiy1YVn4xFClPFrYB",
    "localPath": "/uploads/books/AWS_vs_Azure_vs_Google_vs_IBM_vs_Oracle_vs_Alibaba_A_detailed_comparison.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AWS vs Azure vs Google vs IBM vs Oracle vs Alibaba A detailed comparison. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_12",
    "title": "Azure DevOps Engineer",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1kUWAeAm_cA4QY1Ocjln1FHwtHtNMDkAM/view?usp=sharing",
    "driveFileId": "1kUWAeAm_cA4QY1Ocjln1FHwtHtNMDkAM",
    "localPath": "/uploads/books/Azure DevOps Engineer.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Azure DevOps Engineer. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_13",
    "title": "AZURE Full Course",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1adc8cT3NHxjxizJKLTxeALa4LfW_inyT/view?usp=sharing",
    "driveFileId": "1adc8cT3NHxjxizJKLTxeALa4LfW_inyT",
    "localPath": "/uploads/books/AZURE Full Course.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AZURE Full Course. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_14",
    "title": "Azure&AWS CLoudServiceMap",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1zsrDzSx2OxS3DlfNWA8s6WnhwViLV73Q/view?usp=sharing",
    "driveFileId": "1zsrDzSx2OxS3DlfNWA8s6WnhwViLV73Q",
    "localPath": "/uploads/books/Azure&AWS_CLoudServiceMap.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Azure&AWS CLoudServiceMap. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_15",
    "title": "AzureCertPath",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1t8aikLSY8PHv2QTpdRyGSquEFO9cEr2R/view?usp=sharing",
    "driveFileId": "1t8aikLSY8PHv2QTpdRyGSquEFO9cEr2R",
    "localPath": "/uploads/books/AzureCertPath.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AzureCertPath. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_16",
    "title": "AzureDevOps",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1OmSIzH8GjgRLqkAXaE8oMLEAMDl0XYM5/view?usp=sharing",
    "driveFileId": "1OmSIzH8GjgRLqkAXaE8oMLEAMDl0XYM5",
    "localPath": "/uploads/books/AzureDevOps.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: AzureDevOps. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_17",
    "title": "Basic to Advance Python hand written notes",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Basic to Advance Python hand written notes.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Basic to Advance Python hand written notes.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Basic to Advance Python hand written notes. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_18",
    "title": "Beginning Django CMS (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Beginning Django CMS (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Beginning Django CMS (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Beginning Django CMS (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_19",
    "title": "Complex Network Analysis in Python",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Complex Network Analysis in Python.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Complex Network Analysis in Python.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Complex Network Analysis in Python. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_20",
    "title": "Devops For Dummies",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1IrKluFzsnaQgQXmEsw5dEGoXf2aRoWD8/view?usp=sharing",
    "driveFileId": "1IrKluFzsnaQgQXmEsw5dEGoXf2aRoWD8",
    "localPath": "/uploads/books/Devops For Dummies.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Devops For Dummies. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_21",
    "title": "DevOps 1695290060",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1U0ZfGUakFFz4uCddiDT1hA1afNOhqXIt/view?usp=sharing",
    "driveFileId": "1U0ZfGUakFFz4uCddiDT1hA1afNOhqXIt",
    "localPath": "/uploads/books/DevOps_1695290060.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps 1695290060. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_22",
    "title": "DevOps 1695548180",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1lpcBuqnEtSxbo_KvFtGn7wQixE3d_Ds-/view?usp=sharing",
    "driveFileId": "1lpcBuqnEtSxbo_KvFtGn7wQixE3d_Ds-",
    "localPath": "/uploads/books/DevOps_1695548180.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps 1695548180. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_23",
    "title": "DevOps 1696088085",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1sx1PXRHNhMTLSxDXumXd-TNH6qckYSvJ/view?usp=sharing",
    "driveFileId": "1sx1PXRHNhMTLSxDXumXd-TNH6qckYSvJ",
    "localPath": "/uploads/books/DevOps_1696088085.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps 1696088085. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_24",
    "title": "DevOps 1696443361",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1ihpMjn_edxn7h1kZCcMWCl4YmZe1GWJU/view?usp=sharing",
    "driveFileId": "1ihpMjn_edxn7h1kZCcMWCl4YmZe1GWJU",
    "localPath": "/uploads/books/DevOps_1696443361.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps 1696443361. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_25",
    "title": "DevOps 200 Interview questions 1692564411",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1R5WRVCFOPJcxdHkG8jDob_w94hGj6y7j/view?usp=sharing",
    "driveFileId": "1R5WRVCFOPJcxdHkG8jDob_w94hGj6y7j",
    "localPath": "/uploads/books/DevOps_200_Interview_questions_1692564411.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps 200 Interview questions 1692564411. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_26",
    "title": "DevOps Culture and Practice with OpenShift Deliver continuous business",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1vnDvOp2XUrb_rpIPo7W9m9vzbq3pP7Yt/view?usp=sharing",
    "driveFileId": "1vnDvOp2XUrb_rpIPo7W9m9vzbq3pP7Yt",
    "localPath": "/uploads/books/DevOps_Culture_and_Practice_with_OpenShift_Deliver_continuous_business.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps Culture and Practice with OpenShift Deliver continuous business. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_27",
    "title": "DevOps Interview Questions Answers 1695746349",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1IHLTV42Qi__mQBWgB72YNDgZSE3pCra3/view?usp=sharing",
    "driveFileId": "1IHLTV42Qi__mQBWgB72YNDgZSE3pCra3",
    "localPath": "/uploads/books/DevOps_Interview_Questions_Answers_1695746349.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: DevOps Interview Questions Answers 1695746349. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_28",
    "title": "Learning Python Network Programming (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Learning Python Network Programming (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Learning Python Network Programming (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Learning Python Network Programming (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_29",
    "title": "Mastering Python Networking (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Mastering Python Networking (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Mastering Python Networking (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Mastering Python Networking (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_30",
    "title": "Math Adventures with Python (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Math Adventures with Python (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Math Adventures with Python (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Math Adventures with Python (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_31",
    "title": "Migrating to AWS A Manager's Guide How to Foster Agility, Reduce",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1WRYnnao8bv9RJxqUJ38yoIE6n4oBOiLZ/view?usp=sharing",
    "driveFileId": "1WRYnnao8bv9RJxqUJ38yoIE6n4oBOiLZ",
    "localPath": "/uploads/books/Migrating_to_AWS_A_Manager's_Guide_How_to_Foster_Agility,_Reduce.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Migrating to AWS A Manager's Guide How to Foster Agility, Reduce. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_32",
    "title": "Mobile.DevOps.Playbook",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1eeWvARqaaRG9cCXFuLHwzzZgpFXx1gfK/view?usp=sharing",
    "driveFileId": "1eeWvARqaaRG9cCXFuLHwzzZgpFXx1gfK",
    "localPath": "/uploads/books/Mobile.DevOps.Playbook.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Mobile.DevOps.Playbook. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_33",
    "title": "Natural Language Processing with Python (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Natural Language Processing with Python (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Natural Language Processing with Python (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Natural Language Processing with Python (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_34",
    "title": "Pro Python (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Pro Python (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Pro Python (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Pro Python (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_35",
    "title": "Programming for Computations – Python (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Programming for Computations – Python (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Programming for Computations – Python (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Programming for Computations – Python (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_36",
    "title": "Python for Computational Science and Engineering (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Python for Computational Science and Engineering (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Python for Computational Science and Engineering (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Python for Computational Science and Engineering (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_37",
    "title": "Python for Scientists (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Python for Scientists (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Python for Scientists (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Python for Scientists (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_38",
    "title": "Python Machine Learning Case  Studies (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Python Machine Learning Case  Studies (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Python Machine Learning Case  Studies (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Python Machine Learning Case  Studies (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_39",
    "title": "Python Web Scraping (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Python Web Scraping (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Python Web Scraping (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Python Web Scraping (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_40",
    "title": "Python",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Python.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Python.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Python. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_41",
    "title": "quick-python-book-3rd",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/quick-python-book-3rd.pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/quick-python-book-3rd.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: quick-python-book-3rd. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_42",
    "title": "Serverless Applications with Node",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1JmG3Sz4VHIRTthvczL7fVmmoTgcc1WM4/view?usp=sharing",
    "driveFileId": "1JmG3Sz4VHIRTthvczL7fVmmoTgcc1WM4",
    "localPath": "/uploads/books/Serverless_Applications_with_Node.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Serverless Applications with Node. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_43",
    "title": "Serverless Architecture on AWS Peter",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/1q07OnOaK0K5Uk81_PW9SZRIRnt1FSB4g/view?usp=sharing",
    "driveFileId": "1q07OnOaK0K5Uk81_PW9SZRIRnt1FSB4g",
    "localPath": "/uploads/books/Serverless_Architecture_on_AWS_Peter.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Serverless Architecture on AWS Peter. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_44",
    "title": "Serverless Architectures on AWS Peter Sbarski, Yan Cui, Ajay Nair",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "drive",
    "pdfUrl": "https://drive.google.com/file/d/19s4DpoNoMeOxYyDs5A_Yl3uxaJOwW0iA/view?usp=sharing",
    "driveFileId": "19s4DpoNoMeOxYyDs5A_Yl3uxaJOwW0iA",
    "localPath": "/uploads/books/Serverless_Architectures_on_AWS_Peter_Sbarski,_Yan_Cui,_Ajay_Nair.pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Serverless Architectures on AWS Peter Sbarski, Yan Cui, Ajay Nair. Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_45",
    "title": "Step by Step Guide to Python (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/Step by Step Guide to Python (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/Step by Step Guide to Python (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: Step by Step Guide to Python (en). Available via Google Drive and local library storage."
  },
  {
    "id": "bk_general_46",
    "title": "The Pyramid Web Framework (en)",
    "author": "Sunstone Library",
    "program": "All Programs",
    "category": "Technical",
    "coverUrl": "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=600&q=80",
    "fileType": "file",
    "pdfUrl": "/uploads/books/The Pyramid Web Framework (en).pdf",
    "driveFileId": null,
    "localPath": "/uploads/books/The Pyramid Web Framework (en).pdf",
    "downloadable": true,
    "rating": 4.8,
    "pages": 350,
    "publishedYear": 2024,
    "quickSummary": {
      "highlights": [
        "Comprehensive technical material.",
        "Practical examples and case studies.",
        "Industry standard practices."
      ],
      "keyTakeaways": [
        "Master core technical concepts.",
        "Apply learning to real-world projects."
      ],
      "estimatedReadingTime": "12 Hours",
      "difficultyLevel": "Intermediate to Advanced"
    },
    "description": "A comprehensive technical guide: The Pyramid Web Framework (en). Available via Google Drive and local library storage."
  }
];

export default catalogBooks;
